### ISSUE TITLE
Confusing findBy instructions in Exiting Loops lab

### ISSUE THREAD

**Issue by SaltedC** [learn-co-curriculum/exiting-loops-lab#4]
I found the instructions for the findBy function a little vague.  Another student told me we are supposed to pass each element of the array to findFn, otherwise I would have been completely lost.  From the instructions, I thought we were supposed to get a value from findFn, then see if that value is in array.

- findBy(array, findFn) which looks for a value in arraybased on the return value of findFn. Return null if the value isn't found.

**Comment by adrianhorning08** [comment]
Haha, wow!!! That was SO much easier when I read this. I spent 4 hours on this!!! And then I look back in the Exiting Loops reading....and it was right there... :) Guess I should pay attention to those examples a little more ;) 
However, I agree with SaltedC. I actually thought the exact same thing. However, maybe we didn't understand it because of our lack of understanding.
